global:
  scrape_interval: 1s

# Replace with the current IP of the host machine 
scrape_configs:
  - job_name: open5gs-amfd
    static_configs:
      - targets: ["192.168.56.100:9091"]
  - job_name: open5gs-pcfd
    static_configs:
      - targets: ["192.168.56.100:9092"]
  - job_name: open5gs-smfd
    static_configs:
      - targets: ["192.168.56.100:9093"]
  - job_name: open5gs-upfd
    static_configs:
      - targets: ["192.168.56.100:9094"]
