# -*- mode: ruby -*-
# vi: set ft=ruby :
UERANSIM_IPv4_ADDR = "192.168.56.120"
VM_RAM = "5120"
VM_CPU = "4"
VM_NAME = "ueransim"

Vagrant.configure("2") do |config|

  config.vm.box = "priyanshsingh/UERANSIM"
  config.vm.synced_folder "../shared", "/home/vagrant/shared"
  config.vm.box_check_update = true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "ueransim" do |ueransim|
    ueransim.vm.box = "priyanshsingh/UERANSIM"
    ueransim.vm.network "public_network", ip: UERANSIM_IPv4_ADDR
    ueransim.vm.network :forwarded_port, guest: 5901, host: 5921

    ueransim.vm.provider :virtualbox do |vb|
      vb.name = VM_NAME
      vb.memory = VM_RAM
      vb.cpus = VM_CPU
    end

    ueransim.vm.provider :parallels do |vb|
      vb.memory = VM_RAM
      vb.cpus = VM_CPU
    end

  end
end
