# -*- mode: ruby -*-
# vi: set ft=ruby :
UERANSIM_IPv4_ADDR = "192.168.56.120"
VM_RAM = "512"
VM_CPU = "1"

Vagrant.configure("2") do |config|

  config.vm.box = "priyanshsingh/UERANSIM"
  config.vm.synced_folder "../shared", "/home/vagrant/shared"
  config.vm.box_check_update = true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "ueransim" do |ueransim|
    ueransim.vm.box = "priyanshsingh/UERANSIM"
    ueransim.vm.network "private_network", ip: UERANSIM_IPv4_ADDR
    ueransim.vm.provider :virtualbox do |vb|
      vb.memory = VM_RAM
      vb.cpus = VM_CPU
    end
  end
end
