FROM docker_ueransim:latest

LABEL version="0.0.1"

LABEL maintainer="annanyamehtabest.2001@gmail.com"

WORKDIR /

COPY ueransim_image_init.sh ueransim_image_init.sh
RUN chmod +x ueransim_image_init.sh

