open5gs-nrfd -c nrf.yaml &
open5gs-scpd -c scp.yaml &
open5gs-udmd -c udm.yaml &
open5gs-udrd -c udr.yaml &
open5gs-nssfd -c nssf.yaml &
open5gs-pcfd -c pcf.yaml &
open5gs-bsfd -c bsf.yaml &
open5gs-ausfd -c ausf.yaml &
open5gs-amfd -c amf.yaml &
open5gs-upfd -c upf.yaml &
open5gs-smfd -c smf.yaml &
